server:
  port: 8000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: http://localhost:8761/eureka

spring:
  application:
    name: msa-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: msa-app-user
          uri: lb://MSA-APP-USER
          predicates:
            - Path=/user/**
        - id: msa-app-catalog
          uri: lb://MSA-APP-CATALOG
          predicates:
            - Path=/catalog/**
        - id: msa-app-order
          uri: lb://MSA-APP-ORDER
          predicates:
            - Path=/order/**
        - id: msa-client-app-01
          uri: lb://MSA-CLIENT-APP-01
          predicates:
            - Path=/app01/**
          filters:
#            - AddRequestHeader=app01-gate-in, app01-gate-gogo2
#            - AddResponseHeader=app01-gate-out, app01-gate-byebye2
            - CustomFilter
        - id: msa-client-app-02
          uri: lb://MSA-CLIENT-APP-02
          predicates:
            - Path=/app02/**
          filters:
#            - AddRequestHeader=app02-gate-in, app02-gate-gogo2
#            - AddResponseHeader=app02-gate-out, app02-gate-byebye2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true



