# Use root/example as user/password credentials
version: '3.8'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper-1:
    image: confluentinc/cp-zookeeper:6.2.0
#    hostname: zookeeper
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  zookeeper-2:
    image: confluentinc/cp-zookeeper:6.2.0
#    hostname: zookeeper
    container_name: zookeeper-2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-kafka:6.2.0
#    hostname: broker-1
    container_name: broker-1
    ports:
      - "9091:9091"
      - "29091:29091"
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "host.docker.internal:2181,host.docker.internal:2182"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9091,PLAINTEXT_HOST://host.docker.internal:29091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  broker-2:
    image: confluentinc/cp-kafka:6.2.0
#    hostname: broker-2
    container_name: broker-2
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "host.docker.internal:2181,host.docker.internal:2182"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  broker-3:
    image: confluentinc/cp-kafka:6.2.0
#    hostname: broker-3
    container_name: broker-3
    ports:
      - "9093:9093"
      - "29093:29093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "host.docker.internal:2181,host.docker.internal:2182"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9093,PLAINTEXT_HOST://host.docker.internal:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image:   deltaprojects/kafka-manager:latest
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      KAFKA_MANAGER_AUTH_ENABLED: true # default value
      KAFKA_MANAGER_USERNAME: admin # default value
      KAFKA_MANAGER_PASSWORD: test1234 # default value
      KAFKA_MANAGER_LDAP_ENABLED: false
      KAFKA_MANAGER_EXTRA_PLAY_OPTS: ""
