global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    scrape_interval: 15s
    metrics_path: '/user/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'order-service'
    scrape_interval: 15s
    metrics_path: '/order/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9411']